### PR TITLE
Fixes Permission Errors and Some Spelling Errors

### PR DESCRIPTION
**Pull request by Techno3600**
Hello,

I've got a PR that fixes a bunch of permission errors. The SUPPORT rank does not get Admin permissions, they only get /rank and /givetreasure, (and /givecrate) these are for if a player has lost their stuff whilst a transaction, they also get Junior Developer permissions and lower (because they also need /powerplay). In addition, I was wondering why /rank test was changed from Senior Mod to Admin? I'm pretty sure that Senior Mods get /testrank (or /rank test) now as the QA team needs to test new ranks. Also, "users'" is supposed to be "user's" (check the PR). Lastly, I was looking through the core and I saw that the Developer rank got "mineplex.leader/owner permissions. They don't, they just get Admin permissions.
In my opinion this core not very good, even though it has grown to over and outstanding 5,000 lines of code, downloading really error-spamming add ons is really inconvenient and Skript 2.2 really restricts what you can do and half of the things break anyway like the name tags because the addons error too much. For the next update, what would really bring this plugin back is if Wheezy got another developer to help him code this whole thing into Java. In doing so, he could make it able to work in 1.8+ versions and make it lightweight so it doesn't take so long to load; also, he could make it so you don't have to download a lot of addons and those addons are very annoying and spam my console a lot. These are my thoughts on this core, I know converting it to Java could take some time, but in the long run it would be much better and server owners would consider using it on big servers because it would be more lightweight and easier to run and wouldn't spam errors every half second and would just be easier to develop for future commands. These are my own thoughts and since this is the only remake of the core, a .jar file would make the downloads boost a lot because it would just be so much easier.

### CODE REVIEW

**Comment by NaiculS** [comment]
http://imgur.com/a/PHckF is a command list, it's slightly outdated but should have most commands in the right places with the right description, you might want to go off of this. Aside from a few problems though, this PR looks good. I would say double check all commands for being at correct permissions, and then it should be good. If you could add /check also, that would be insane though...

**Comment by NaiculS** [comment]
You should modify Dev perms to be updated, and see if you can give Sr. Mod /rank test.

**Comment by Techno3600** [comment]
I think I got all the commands correct, I made sure that support had /updaterank and PPC which is all they need, Jr.Dev also gets these but not the /updaterank, they just get /testrank which is why I gave Support “Mineplex.jrdev” and not the other way around (which would be goving Jr.Dev “Mineplex.support”, the rank’s permissions do get a little confusing here because support, instead of being on a set rank ladder, it takes Jr.Dev permissions and a few others. If you could specify what I could improve that would be great @NaiculS . Thanks!

**Comment by Techno3600** [comment]
Also what does /check do in the first place?

**Comment by xMRENDERMAN** [comment]
/Check let’s support+ members see a player's shards, gems, treasure chests, packages, etc. and let’s them add certain packages or said shares, gems, treasure chests, packages, etc.

This also includes special limited time items.

**Comment by jimmy13811** [comment]
When I do /set rank user ADMIN 
or any rank it tells me invalid rank how can i fix this

**Comment by xMRENDERMAN** [comment]
@jimmy13811 The command usage to set a rank is

- /rank set (Player) (Rank)

**Comment by jimmy13811** [comment]
I still get invalid rank 
in the server files i changed me to Admin and my friend to mod and mods cant /p

**Comment by xMRENDERMAN** [comment]
Have you tried running it from console?

**Comment by NaiculS** [comment]
Move this to discord please @xMRENDERMAN @jimmy13811

**Comment by xMRENDERMAN** [comment]
@NaiculS 10-04

**Comment by JRoy** [comment]
Added in 3.1 😃

**Pull request closed without merging**
